apiVersion: apps/v1
kind: Deployment
metadata:
  name:  webook
  namespace: default
  labels:
    app:  webook
spec:
  selector:
    matchLabels:
      app: webook
  replicas: 1
  template:
    metadata:
      labels:
        app:  webook
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name:  webook-service
          image:  novo/webook:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort:  8080
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always