---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by novo.
--- DateTime: 2024/11/4 23:56
---
local codeKey = KEYS[1]
local codeVal = ARGV[1]
-- 允许验证次数的key
local cntKey = codeKey..':cnt'

-- 这里选择使用ttl的方案来获取过期时间，也可以选择 code_timestamp的方案
-- https://redis.io/docs/latest/commands/ttl/
local ttl = tonumber(redis.call('ttl', codeKey))

-- key 存在但是没有过期时间，异常情况
if ttl == -1 then
    return -2
-- key 不存在或者 key已经存在1分钟 过期时间10min=600s
-- 允许发送验证码
elseif ttl == -2 or ttl < 540 then
    redis.call('set', codeKey, codeVal)
    redis.call('expire', codeKey, 600)
    redis.call('set', cntKey, 3)
    redis.call('expire', cntKey, 600)
    return 0
-- 发送频繁
else
    return -1
end