// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package router

import (
	"webook/internal/handler"
	"webook/internal/repository"
	"webook/internal/repository/cache"
	"webook/internal/repository/database"
	"webook/internal/service"
)

// Injectors from wire.go:

func InitUserRouter() *UserRouter {
	db := database.Init()
	userDAO := database.NewUserDAO(db)
	cmdable := cache.Init()
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := cache.NewCodeCache(cmdable)
	codeService := service.NewCodeService(codeCache)
	userHandler := handler.NewUserHandler(userService, codeService)
	userRouter := NewUserRouter(userHandler)
	return userRouter
}
